export const dataInput = [
  {
    id: 1,
    question: "Вы старше 18?",
    answer_1: "Не выбрано",
    answer_2: "Старше",
    answer_3: "Младше",
    answer_4: "Мне 18",
  },
  {
    id: 2,
    question: "У Вас есть хобби?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "",
  },
  {
    id: 3,
    question: "Вы занимаетесь спортом?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "",
  },
  {
    id: 4,
    question: "Любите домашних животных?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "Нейтрально",
  },
  {
    id: 5,
    question: "Левша или правша?",
    answer_1: "Не выбрано",
    answer_2: "Левша",
    answer_3: "Правша",
    answer_4: "",
  },
  {
    id: 6,
    question: "У вас есть возлюбленный(краш)?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "",
  },
  {
    id: 7,
    question: "Вы верующий человек?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "50/50",
  },
  {
    id: 8,
    question:
      "Вы бывали на грани смерти? ( Тонули, убегали от маньяка, попадали в аварию и т.д )",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "",
  },
  {
    id: 9,
    question: "Верите в реинкарнацию ( жизнь после смерти )?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "",
  },
  {
    id: 10,
    question: "У Вас есть фобии?",
    answer_1: "Не выбрано",
    answer_2: "Да",
    answer_3: "Нет",
    answer_4: "",
  },
];
